# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ecg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ecg.proto',
  package='ecg',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\tecg.proto\x12\x03\x65\x63g\"\xa2\x02\n\tECGPacket\x12+\n\x07\x63ommand\x18\x01 \x01(\x0e\x32\x1a.ecg.ECGPacket.CommandType\x12\x11\n\tdevice_id\x18\x02 \x01(\t\x12\x13\n\x0bsequence_id\x18\x03 \x01(\x05\x12\r\n\x05value\x18\x04 \x01(\x05\x12\x0f\n\x07\x62\x61ttery\x18\x05 \x01(\r\x12\x0e\n\x06\x61\x63tive\x18\x06 \x01(\x08\x12\x0c\n\x04time\x18\x07 \x01(\x04\x12*\n\tdata_type\x18\x08 \x01(\x0e\x32\x17.ecg.ECGPacket.DataType\"-\n\x0b\x43ommandType\x12\x07\n\x03NEW\x10\x00\x12\n\n\x06UPDATE\x10\x01\x12\t\n\x05\x43LOSE\x10\x02\"\'\n\x08\x44\x61taType\x12\x07\n\x03RRI\x10\x00\x12\x08\n\x04TEMP\x10\x01\x12\x08\n\x04SPO2\x10\x02\x62\x06proto3')
)



_ECGPACKET_COMMANDTYPE = _descriptor.EnumDescriptor(
  name='CommandType',
  full_name='ecg.ECGPacket.CommandType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NEW', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UPDATE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLOSE', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=223,
  serialized_end=268,
)
_sym_db.RegisterEnumDescriptor(_ECGPACKET_COMMANDTYPE)

_ECGPACKET_DATATYPE = _descriptor.EnumDescriptor(
  name='DataType',
  full_name='ecg.ECGPacket.DataType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RRI', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TEMP', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SPO2', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=270,
  serialized_end=309,
)
_sym_db.RegisterEnumDescriptor(_ECGPACKET_DATATYPE)


_ECGPACKET = _descriptor.Descriptor(
  name='ECGPacket',
  full_name='ecg.ECGPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='ecg.ECGPacket.command', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device_id', full_name='ecg.ECGPacket.device_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sequence_id', full_name='ecg.ECGPacket.sequence_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='ecg.ECGPacket.value', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='battery', full_name='ecg.ECGPacket.battery', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='active', full_name='ecg.ECGPacket.active', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='ecg.ECGPacket.time', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_type', full_name='ecg.ECGPacket.data_type', index=7,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ECGPACKET_COMMANDTYPE,
    _ECGPACKET_DATATYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=309,
)

_ECGPACKET.fields_by_name['command'].enum_type = _ECGPACKET_COMMANDTYPE
_ECGPACKET.fields_by_name['data_type'].enum_type = _ECGPACKET_DATATYPE
_ECGPACKET_COMMANDTYPE.containing_type = _ECGPACKET
_ECGPACKET_DATATYPE.containing_type = _ECGPACKET
DESCRIPTOR.message_types_by_name['ECGPacket'] = _ECGPACKET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ECGPacket = _reflection.GeneratedProtocolMessageType('ECGPacket', (_message.Message,), {
  'DESCRIPTOR' : _ECGPACKET,
  '__module__' : 'ecg_pb2'
  # @@protoc_insertion_point(class_scope:ecg.ECGPacket)
  })
_sym_db.RegisterMessage(ECGPacket)


# @@protoc_insertion_point(module_scope)
